from __future__ import annotations

import os
import tempfile

from fastapi import APIRouter
from pydantic import BaseModel, Field

from server.git.mr import create_mr
from server.git.ops import run_git
from server.git.review import review_diff

router = APIRouter(prefix="/git", tags=["git"])


class CommitBody(BaseModel):
    message: str | None = None


class ReviewBody(BaseModel):
    diff: str = Field(..., min_length=1)


class MrBody(BaseModel):
    title: str
    body: str
    base: str | None = None


@router.post("/commit")
async def git_commit(body: CommitBody) -> dict:
    msg = (body.message or "chore: checkpoint").strip()
    await run_git("add", "-A")
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".gitmsg.txt",
        delete=False,
        encoding="utf-8",
    ) as f:
        f.write(msg)
        path = f.name
    try:
        await run_git("commit", "-F", path)
    finally:
        try:
            os.unlink(path)
        except OSError:
            pass
    code, out, _ = await run_git("rev-parse", "HEAD", check=False)
    h = out.strip() if code == 0 else ""
    return {"hash": h, "message": msg}


@router.post("/review")
async def git_review(body: ReviewBody) -> dict:
    return await review_diff(body.diff)


@router.post("/mr")
async def git_mr(body: MrBody) -> dict:
    url = await create_mr(body.title, body.body + "\n\nGenerated by Crux.", base=body.base)
    return {"url": url}


@router.get("/status")
async def git_status() -> dict:
    code, branch, _ = await run_git("rev-parse", "--abbrev-ref", "HEAD", check=False)
    br = branch.strip() if code == 0 else "unknown"
    code, por, _ = await run_git("status", "--porcelain", check=False)
    changes = len([ln for ln in por.splitlines() if ln.strip()]) if code == 0 else 0
    code, last, _ = await run_git("log", "-1", "--oneline", check=False)
    return {"branch": br, "change_count": changes, "last_commit": last.strip() if code == 0 else ""}
